//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scryber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scryber.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style list can only merge &apos;{0}&apos; style items with &apos;{0}&apos; style items. The merging item &apos;{1}&apos; is not of the same type..
        /// </summary>
        internal static string CanOnlyMergeItemsOfSameType {
            get {
                return ResourceManager.GetString("CanOnlyMergeItemsOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All external defined files must have a base type of &apos;{0}&apos;..
        /// </summary>
        internal static string CanOnlyReferenceExternalStyleDefinitionsOfType {
            get {
                return ResourceManager.GetString("CanOnlyReferenceExternalStyleDefinitionsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the {0} from the style : {1}.
        /// </summary>
        internal static string CouldNotCreateTheGraphicObjectFromTheStyle {
            get {
                return ResourceManager.GetString("CouldNotCreateTheGraphicObjectFromTheStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of an external file &apos;{0}&apos; is not supported in the base document class..
        /// </summary>
        internal static string LoadingOfExternalFilesNotSupported {
            get {
                return ResourceManager.GetString("LoadingOfExternalFilesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current component in this Layout Engine. Ensure the engine is in the process of laying out a container before calling this method..
        /// </summary>
        internal static string NoCurrentComponentInLayoutEngine {
            get {
                return ResourceManager.GetString("NoCurrentComponentInLayoutEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style key &apos;{0}&apos; is not a recognised style key.
        /// </summary>
        internal static string StyleItemNotFound {
            get {
                return ResourceManager.GetString("StyleItemNotFound", resourceCulture);
            }
        }
    }
}
