//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scryber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scryber.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks that are absolute positioned must be registered with the page rather than on an inner block..
        /// </summary>
        internal static string AbsolutePositioningBlocksRegisterWithTheLayoutPage {
            get {
                return ResourceManager.GetString("AbsolutePositioningBlocksRegisterWithTheLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font with name &apos;{0}&apos; is not a standard font, This font must be referenced in the configuration file or have the file path specified. .
        /// </summary>
        internal static string AFontWithNameMustBeDeclaredInConfig {
            get {
                return ResourceManager.GetString("AFontWithNameMustBeDeclaredInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a header layout defined on this layout page.
        /// </summary>
        internal static string AlreadyAHeaderDefinedOnPage {
            get {
                return ResourceManager.GetString("AlreadyAHeaderDefinedOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strong named assembly token does not match the licensed component.
        /// </summary>
        internal static string AssembyTokensDoNotMatchOnLicense {
            get {
                return ResourceManager.GetString("AssembyTokensDoNotMatchOnLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component with the id &apos;{0}&apos; does not implement the IPDFDataSource interface. All Components that are to be used as datasources must implement this interface..
        /// </summary>
        internal static string AssignedDataSourceIsNotIPDFDataSource {
            get {
                return ResourceManager.GetString("AssignedDataSourceIsNotIPDFDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assigned datasource for the binding component does not implement the IXPathNavigable interface. All datasources that are to be used must implement this interface..
        /// </summary>
        internal static string AssignedDataSourceIsNotNavigable {
            get {
                return ResourceManager.GetString("AssignedDataSourceIsNotNavigable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the offset {0} in the table with a {1} count of {2}.
        /// </summary>
        internal static string CannotAccessGridOffsetInTable {
            get {
                return ResourceManager.GetString("CannotAccessGridOffsetInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the stream until its initial position has been set. Please use the Read() method before tring to access the stream..
        /// </summary>
        internal static string CannotAccessStreamWithoutRead {
            get {
                return ResourceManager.GetString("CannotAccessStreamWithoutRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the cell reference to the column at row {0} because it is already full. Ensure that the cells are added in order to a column..
        /// </summary>
        internal static string CannotAddCellToIndexAlreadyFull {
            get {
                return ResourceManager.GetString("CannotAddCellToIndexAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline components do not have surrounding blocks..
        /// </summary>
        internal static string CannotBeginABlockThatIsInline {
            get {
                return ResourceManager.GetString("CannotBeginABlockThatIsInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The created style item returned from the Document could not be cast to a {0} item..
        /// </summary>
        internal static string CannotCastToStyleItem {
            get {
                return ResourceManager.GetString("CannotCastToStyleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This placeholder has already parsed it&apos;s contents, and can no longer be modifed..
        /// </summary>
        internal static string CannotChangeTheContentsOfAPlaceHolderOnceParsed {
            get {
                return ResourceManager.GetString("CannotChangeTheContentsOfAPlaceHolderOnceParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; cannot be changed because the item &apos;{1}&apos; is locked for rendering.
        /// </summary>
        internal static string CannotChangeValueWhenLocked {
            get {
                return ResourceManager.GetString("CannotChangeValueWhenLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &apos;{0}&apos; cannot be cast to the required &apos;{1}&apos; type..
        /// </summary>
        internal static string CannotConvertObjectToType {
            get {
                return ResourceManager.GetString("CannotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of type &apos;{0}&apos; could not be created. {1}.
        /// </summary>
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of the type &apos;{0}&apos; required by the object command &apos;{1}&apos; could not be created. A public parameterless constructor is needed on the declaring type for instance methods to be used..
        /// </summary>
        internal static string CannotCreateInstanceOfTypeOnCommand {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfTypeOnCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a regular ploygon shape with less than 3 sides (it&apos;s not a shape)..
        /// </summary>
        internal static string CannotCreatePolygonWithLessThan3Sides {
            get {
                return ResourceManager.GetString("CannotCreatePolygonWithLessThan3Sides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a regular ploygram shape with less than 5 sides (it&apos;s not a shape)..
        /// </summary>
        internal static string CannotCreatePolygramWithLessThan5Sides {
            get {
                return ResourceManager.GetString("CannotCreatePolygramWithLessThan5Sides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All namespaces must have a prefix explictly set for all elements that are in a namespace. The namespace &apos;{0}&apos; does not have a prefix assigned..
        /// </summary>
        internal static string CannotDeclareNamespaceWithoutPrefix {
            get {
                return ResourceManager.GetString("CannotDeclareNamespaceWithoutPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize the license data for component {0}. See the inner exception for more details..
        /// </summary>
        internal static string CannotDeserializePDFLicenceFromData {
            get {
                return ResourceManager.GetString("CannotDeserializePDFLicenceFromData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an error to attempt to end the layout of a component that is not the current component..
        /// </summary>
        internal static string CannotEndAComponentLayoutIfNotCurrent {
            get {
                return ResourceManager.GetString("CannotEndAComponentLayoutIfNotCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transformed SQL data source no longer support schema extraction..
        /// </summary>
        internal static string CannotGetSchemaForTransformedSource {
            get {
                return ResourceManager.GetString("CannotGetSchemaForTransformedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot alter the layout of a block that has been closed. Check the IsClosed property before trying to append.
        /// </summary>
        internal static string CannotLayoutABlockThatHasBeenClosed {
            get {
                return ResourceManager.GetString("CannotLayoutABlockThatHasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot alter the layout of a page that has been closed..
        /// </summary>
        internal static string CannotLayoutAPageThatHasBeenClosed {
            get {
                return ResourceManager.GetString("CannotLayoutAPageThatHasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method must be called with an absolute path (not relative). Use the MapPath method to attempt conversion from a relative to an absolute path..
        /// </summary>
        internal static string CannotLoadFileWithRelativePath {
            get {
                return ResourceManager.GetString("CannotLoadFileWithRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group of table grid sizes has been locked and cannot be modified, only read..
        /// </summary>
        internal static string CannotModifyTableGridSizes {
            get {
                return ResourceManager.GetString("CannotModifyTableGridSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an error to attempt to read past the end of the stream. Use the bool Read() return value before accessing the stream values..
        /// </summary>
        internal static string CannotReadPastTheEOF {
            get {
                return ResourceManager.GetString("CannotReadPastTheEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original parsed source does not have a root location. Cannot parse referenced files from an un-rooted source unless they are full / absolute paths..
        /// </summary>
        internal static string CannotReferenceExternalFilesFromSourcesWithoutARoot {
            get {
                return ResourceManager.GetString("CannotReferenceExternalFilesFromSourcesWithoutARoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license could not be serialized to the provided stream. See te inner exception for more details..
        /// </summary>
        internal static string CannotSerializePDFLicenceToStream {
            get {
                return ResourceManager.GetString("CannotSerializePDFLicenceToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base text value of the PageNumberLabel cannot be set explicity. This is derived at render time from the format value and current page numbers.
        /// </summary>
        internal static string CannotSetBaseTextOfPageNumber {
            get {
                return ResourceManager.GetString("CannotSetBaseTextOfPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set both the DataSource value and the DataSourceID value of a binding control. Ensure that the unused property is clear before setting the required property..
        /// </summary>
        internal static string CannotSetDataSourceAndDataSourceID {
            get {
                return ResourceManager.GetString("CannotSetDataSourceAndDataSourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A viewport component cannot be set with a layout mode of inline..
        /// </summary>
        internal static string CannotSetViewPortAsInline {
            get {
                return ResourceManager.GetString("CannotSetViewPortAsInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting of the &apos;Template&apos; property is not supported in the PDFChoose Component. Use the Where and Otherwise properties instead..
        /// </summary>
        internal static string CannotUseBaseTemplateInChoose {
            get {
                return ResourceManager.GetString("CannotUseBaseTemplateInChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use the FindComponent method when an Component is not contained within the document heirarchy..
        /// </summary>
        internal static string CannotUseFindForComponentNotInDocumentHeirarchy {
            get {
                return ResourceManager.GetString("CannotUseFindForComponentNotInDocumentHeirarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All external defined files must have a base type of &apos;{0}&apos;..
        /// </summary>
        internal static string CanOnlyReferenceExternalStyleDefinitionsOfType {
            get {
                return ResourceManager.GetString("CanOnlyReferenceExternalStyleDefinitionsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of a positioned region we expected to be a single layout block. Transformations are only supported on the standard block elements such as panels and divs..
        /// </summary>
        internal static string CanOnlyTransformBlockComponents {
            get {
                return ResourceManager.GetString("CanOnlyTransformBlockComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parsed documents have a circular dependancy reference to the path &apos;{0}&apos;. Please check the references..
        /// </summary>
        internal static string CircularReferenceToPath {
            get {
                return ResourceManager.GetString("CircularReferenceToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color space &apos;{0}&apos; is not supported. The PDFX graphics system currently only supports RGB and Gray color spaces, other values of the enumeration are there for future use..
        /// </summary>
        internal static string ColorValueIsNotCurrentlySupported {
            get {
                return ResourceManager.GetString("ColorValueIsNotCurrentlySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The releated data command for type {0} must be of type {1}.
        /// </summary>
        internal static string CommandForRelatedDataMustMatchType {
            get {
                return ResourceManager.GetString("CommandForRelatedDataMustMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Provider command with the name &apos;{0}&apos; could not be found in the source &apos;{1}&apos;. Names are case-sensitive..
        /// </summary>
        internal static string CommandWithNameCannotBeFound {
            get {
                return ResourceManager.GetString("CommandWithNameCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component with type &apos;{0}&apos; is not a known Component for the layout engine. Either change its type, make the type implement the IPDFComponentViewPort interface, or sets its type to NoOp..
        /// </summary>
        internal static string ComponentIsNotKnownToLayoutEngine {
            get {
                return ResourceManager.GetString("ComponentIsNotKnownToLayoutEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A component with the name &apos;{0}&apos; has already been registered in this document. It is an error to have 2 components in the same name in the same document..
        /// </summary>
        internal static string ComponentNamerAlreadyRegistered {
            get {
                return ResourceManager.GetString("ComponentNamerAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building and binding the required components in the data list to the current data source failed. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotBindDataComponent {
            get {
                return ResourceManager.GetString("CouldNotBindDataComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TableGrid could not be built for the table &apos;{0}&apos;. See the inner exception for more details.
        /// </summary>
        internal static string CouldNotBuildTheTableGrid {
            get {
                return ResourceManager.GetString("CouldNotBuildTheTableGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object could not be converted to Xml. Please see the inner exception for more details..
        /// </summary>
        internal static string CouldNotConvertObjectToXml {
            get {
                return ResourceManager.GetString("CouldNotConvertObjectToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize the licence terms. An error occurred whilst reading the fields. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotDeserializeTheLicenseTerms {
            get {
                return ResourceManager.GetString("CouldNotDeserializeTheLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode image could not be downloaded from the specified url: {0}.
        /// </summary>
        internal static string CouldNotDownloadBarcodeData {
            get {
                return ResourceManager.GetString("CouldNotDownloadBarcodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fill the graphics context with the specific text due to the error : {0}.
        /// </summary>
        internal static string CouldNotFillText {
            get {
                return ResourceManager.GetString("CouldNotFillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component with the id &apos;{0}&apos; could not be found. The search is case sensitive..
        /// </summary>
        internal static string CouldNotFindControlWithID {
            get {
                return ResourceManager.GetString("CouldNotFindControlWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A component with name &apos;{0}&apos; could not be found. The search is case sensitive. To look up an ID, prefix with #.
        /// </summary>
        internal static string CouldNotFindControlWithName {
            get {
                return ResourceManager.GetString("CouldNotFindControlWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initialization and image load for component {0} failed. See inner exception for more details.
        /// </summary>
        internal static string CouldNotInitializeTheImageForComponent {
            get {
                return ResourceManager.GetString("CouldNotInitializeTheImageForComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not layout the cells of the table grid with id &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string CouldNotLayoutGridCells {
            get {
                return ResourceManager.GetString("CouldNotLayoutGridCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested assembly &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string CouldNotLoadAssembly {
            get {
                return ResourceManager.GetString("CouldNotLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image path could not be resolved, or the image could not be loaded from path &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotLoadImageFromPath {
            get {
                return ResourceManager.GetString("CouldNotLoadImageFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the license key for component {0}. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotLoadLicenceKey {
            get {
                return ResourceManager.GetString("CouldNotLoadLicenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source data could not be loaded from the data provider with id &apos;{0}&apos;. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotLoadTheDataFromProvider {
            get {
                return ResourceManager.GetString("CouldNotLoadTheDataFromProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} data source could not be retrieved from the requested path. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotLoadTheDataFromTheSourcePath {
            get {
                return ResourceManager.GetString("CouldNotLoadTheDataFromTheSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fall back missing image could not be found, so cannot replace the not found image..
        /// </summary>
        internal static string CouldNotLoadTheMissingImage {
            get {
                return ResourceManager.GetString("CouldNotLoadTheMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested type &apos;{0}&apos; could not be loaded from the requested assembly..
        /// </summary>
        internal static string CouldNotLoadType {
            get {
                return ResourceManager.GetString("CouldNotLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance. A value in the format &apos;{2}&apos;.
        /// </summary>
        internal static string CouldNotParseTheValue_3 {
            get {
                return ResourceManager.GetString("CouldNotParseTheValue_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance..
        /// </summary>
        internal static string CouldNotParseValue_2 {
            get {
                return ResourceManager.GetString("CouldNotParseValue_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance..
        /// </summary>
        internal static string CouldNotParseValue_21 {
            get {
                return ResourceManager.GetString("CouldNotParseValue_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance. A value in the format &apos;{2}&apos; was expected..
        /// </summary>
        internal static string CouldNotParseValue_3 {
            get {
                return ResourceManager.GetString("CouldNotParseValue_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst trying to extract the data..
        /// </summary>
        internal static string CouldNotSelectData {
            get {
                return ResourceManager.GetString("CouldNotSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transformation of the data failed. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotTransformInputData {
            get {
                return ResourceManager.GetString("CouldNotTransformInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded data could not be transformed by the specified file. See the inner exception for more details..
        /// </summary>
        internal static string CouldNotTransformResult {
            get {
                return ResourceManager.GetString("CouldNotTransformResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided binary data could not be converted to a required Bitmap instance. Ensure the data is a bitmap..
        /// </summary>
        internal static string CountNoConvertBinaryDataToBitmap {
            get {
                return ResourceManager.GetString("CountNoConvertBinaryDataToBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; on data source &apos;{1}&apos; failed to load the data. See the inner exception for more details..
        /// </summary>
        internal static string DataLoadFailedForCommand {
            get {
                return ResourceManager.GetString("DataLoadFailedForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data source does not support extraction of the data schema. Always ceck the Suports property before calling this method..
        /// </summary>
        internal static string DataSchemaExtractionIsNotSupported {
            get {
                return ResourceManager.GetString("DataSchemaExtractionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data schema item was found at the path &apos;{0}&apos;..
        /// </summary>
        internal static string DataSchemaItemNotFoundAtPath {
            get {
                return ResourceManager.GetString("DataSchemaItemNotFoundAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document component cannot be bound at this stage. It has already been laid out..
        /// </summary>
        internal static string DocumentCannotBeBoundAtThisStage {
            get {
                return ResourceManager.GetString("DocumentCannotBeBoundAtThisStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has already been initialized. It cannot be initialized more than once..
        /// </summary>
        internal static string DocumentHasAlreadyBeenInitialized {
            get {
                return ResourceManager.GetString("DocumentHasAlreadyBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has already been loaded. It cannot be loaded more than once..
        /// </summary>
        internal static string DocumentHasAlreadyBeenLoaded {
            get {
                return ResourceManager.GetString("DocumentHasAlreadyBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has already been disposed. It cannot take part in any activities once it has been disposed..
        /// </summary>
        internal static string DocumentHasBeenDisposed {
            get {
                return ResourceManager.GetString("DocumentHasBeenDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has not been initialised. It cannot perform further actions until it has been initiaized..
        /// </summary>
        internal static string DocumentHasNotBeenInitialized {
            get {
                return ResourceManager.GetString("DocumentHasNotBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDFDocument has not been laidout, and cannot perfrom further generation stages out of sequence..
        /// </summary>
        internal static string DocumentHasNotBeenLaidout {
            get {
                return ResourceManager.GetString("DocumentHasNotBeenLaidout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDFDocument has not been loaded, and cannot perfrom further generation stages out of sequence..
        /// </summary>
        internal static string DocumentHasNotBeenLoaded {
            get {
                return ResourceManager.GetString("DocumentHasNotBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object datasource &apos;{0}&apos; could not load the data because : {1}.
        /// </summary>
        internal static string FailedToLoadDataForObjectSource {
            get {
                return ResourceManager.GetString("FailedToLoadDataForObjectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file could not be found at the specified path. Or the file is not a valid XML document..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no font file associated with the font definition &apos;{0}&apos;.
        /// </summary>
        internal static string FontDefinitionDoesNotHaveFile {
            get {
                return ResourceManager.GetString("FontDefinitionDoesNotHaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font &apos;{0} {1}&apos; has not been registered with the current resource section. Fonts must be registered with the current page or IResourceContainer before use. This is normally done with the PDFGraphics DrawString and DrawTextBlock methods..
        /// </summary>
        internal static string FontNotRegistered {
            get {
                return ResourceManager.GetString("FontNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDFGraphics class only supports the TopDown DrawingOrigin.
        /// </summary>
        internal static string GraphicsOnlySupportsTopDownDrawing {
            get {
                return ResourceManager.GetString("GraphicsOnlySupportsTopDownDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table has not been measured or the referenced grid has been lost..
        /// </summary>
        internal static string GridIsNullNotMeasured {
            get {
                return ResourceManager.GetString("GridIsNullNotMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CloseGrid method has not been called after adding cells to the table grid. .
        /// </summary>
        internal static string GridNotClosed {
            get {
                return ResourceManager.GetString("GridNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This indirect object has already been written to the underlying stream. Cannot write the same object twice.
        /// </summary>
        internal static string IndirectObjectHasAlreadyBeenWritten {
            get {
                return ResourceManager.GetString("IndirectObjectHasAlreadyBeenWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hierarchy is not complete. No parent exists that can create a graphics context for the requesting Component..
        /// </summary>
        internal static string InvalidCallToGetGraphicsForStructure {
            get {
                return ResourceManager.GetString("InvalidCallToGetGraphicsForStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unit cannot be instantiated with &apos;Empty&apos;, please specify the actual unit of measurement.
        /// </summary>
        internal static string InvalidEmptyUnits {
            get {
                return ResourceManager.GetString("InvalidEmptyUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XPath expression &apos;{0}&apos; could not be evaluated. Please check the statement..
        /// </summary>
        internal static string InvalidXPathExpression {
            get {
                return ResourceManager.GetString("InvalidXPathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform this action, as the current item in this container has not been closed. Close the current item first, then perform the action..
        /// </summary>
        internal static string LayoutContainerHasExistingOpenItem {
            get {
                return ResourceManager.GetString("LayoutContainerHasExistingOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDFComponentArangement has not been set on this Component before attempting to render. All Components must have their arrangement set before rendering..
        /// </summary>
        internal static string LayoutEngineHasNotSetArrangement {
            get {
                return ResourceManager.GetString("LayoutEngineHasNotSetArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout engine is already positioning a component. You cannot use the same engine to run more than one component at a time.
        /// </summary>
        internal static string LayoutEngineIsAlreadyWorking {
            get {
                return ResourceManager.GetString("LayoutEngineIsAlreadyWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout of component &apos;{0}&apos; failed. {1}.
        /// </summary>
        internal static string LayoutFailedForComponent {
            get {
                return ResourceManager.GetString("LayoutFailedForComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout item could not be closed. .
        /// </summary>
        internal static string LayoutItemCouldNotBeClosed {
            get {
                return ResourceManager.GetString("LayoutItemCouldNotBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This layout item is closed and cannot be appended to.
        /// </summary>
        internal static string LayoutItemIsClosed {
            get {
                return ResourceManager.GetString("LayoutItemIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout manager already has an open {0}. Please close the current {0} before starting a new one..
        /// </summary>
        internal static string LayoutManagerAlreadyHasAnOpenItem {
            get {
                return ResourceManager.GetString("LayoutManagerAlreadyHasAnOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout item does not have a currently open line available to close. Check the HasOpenLine property first..
        /// </summary>
        internal static string LayoutNoCurrentLineToClose {
            get {
                return ResourceManager.GetString("LayoutNoCurrentLineToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license signature is invalid for the specified terms..
        /// </summary>
        internal static string LicenseSignatureCouldNotBeValidated {
            get {
                return ResourceManager.GetString("LicenseSignatureCouldNotBeValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching destination to &apos;{0}&apos; could be found. The link cannot be assigned..
        /// </summary>
        internal static string LinkToDestinationCouldNotBeMade {
            get {
                return ResourceManager.GetString("LinkToDestinationCouldNotBeMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of an external file &apos;{0}&apos; is not supported in the base document class..
        /// </summary>
        internal static string LoadingOfExternalFilesNotSupported {
            get {
                return ResourceManager.GetString("LoadingOfExternalFilesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; found on type {1}does not match the signature declared by the object command &apos;{2}&apos; in the data source {3}. Ensure all required methods are publicly accessible..
        /// </summary>
        internal static string MatchingMethodSignatureCouldNotBeFoundForObjectData {
            get {
                return ResourceManager.GetString("MatchingMethodSignatureCouldNotBeFoundForObjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; found on type {1}does not have a return type, so cannot be used as declared by the object command &apos;{2}&apos; in the data source {3}. Ensure all required methods are publicly accessible..
        /// </summary>
        internal static string MatchingMethodSignatureDoesNotHaveAReturnTypeObjectData {
            get {
                return ResourceManager.GetString("MatchingMethodSignatureDoesNotHaveAReturnTypeObjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Measure and Arrange methods must be called on an object before it can be rendered..
        /// </summary>
        internal static string MeasureNotCalled {
            get {
                return ResourceManager.GetString("MeasureNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Measure and Arrange methods must be called on an object before it can be rendered..
        /// </summary>
        internal static string MeasureNotCalled1 {
            get {
                return ResourceManager.GetString("MeasureNotCalled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; could not be found on type {1} required by object command &apos;{2}&apos; in the data source {3}. Ensure all required methods are publicly accessible..
        /// </summary>
        internal static string MethodCouldNotBeFoundForObjectData {
            get {
                return ResourceManager.GetString("MethodCouldNotBeFoundForObjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Method name to call for the Object Command &apos;{0}&apos; has not been set in the data source &apos;{1}&apos;.
        /// </summary>
        internal static string MethodNameNotSetOnObjectDataSource {
            get {
                return ResourceManager.GetString("MethodNameNotSetOnObjectDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registered method has parameter &apos;{0}&apos; which has not been specified. All parameters must be declared on the command..
        /// </summary>
        internal static string MethodParameterNotDefinedWithName {
            get {
                return ResourceManager.GetString("MethodParameterNotDefinedWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified start index for a page modification is longer than the current base file..
        /// </summary>
        internal static string ModificationStartIndexIsLongerThanDocument {
            get {
                return ResourceManager.GetString("ModificationStartIndexIsLongerThanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified count for page modifications goes beyond the current base file page count, starting at the specified index..
        /// </summary>
        internal static string ModificationStartIndexPlusCountIsLongerThanDocument {
            get {
                return ResourceManager.GetString("ModificationStartIndexPlusCountIsLongerThanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection defined on this command &apos;{0}&apos; in datasource &apos;{1}&apos;..
        /// </summary>
        internal static string NoConnectionDefined {
            get {
                return ResourceManager.GetString("NoConnectionDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file does not contain a connection setting with the name &apos;{0}&apos;..
        /// </summary>
        internal static string NoConnectionSettingFor {
            get {
                return ResourceManager.GetString("NoConnectionSettingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current component in this Layout Engine. Ensure the engine is in the process of laying out a container before calling this method..
        /// </summary>
        internal static string NoCurrentComponentInLayoutEngine {
            get {
                return ResourceManager.GetString("NoCurrentComponentInLayoutEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current number group in the list numbering to action. Groups must be opended before they can be used/.
        /// </summary>
        internal static string NoCurrentNumberGroup {
            get {
                return ResourceManager.GetString("NoCurrentNumberGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no currently open table layout cell on the row. .
        /// </summary>
        internal static string NoCurrentOpenTableCell {
            get {
                return ResourceManager.GetString("NoCurrentOpenTableCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default value has been set on the parameter &apos;{0}&apos; which has a value type &apos;{1}&apos;. Cannot pass null to this parameter, so a default value is required..
        /// </summary>
        internal static string NoDefaultValueSetOnEmptyValueTypeParameter {
            get {
                return ResourceManager.GetString("NoDefaultValueSetOnEmptyValueTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link of type Uri was specified, but no value was specified for the file to navigate to. Please specify a File value..
        /// </summary>
        internal static string NoFileLinkSpecifiedOnUriAction {
            get {
                return ResourceManager.GetString("NoFileLinkSpecifiedOnUriAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current footer block on this layout page to close. .
        /// </summary>
        internal static string NoFooterBlockToClose {
            get {
                return ResourceManager.GetString("NoFooterBlockToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current header block on this layout page to close.
        /// </summary>
        internal static string NoHeaderBlockToClose {
            get {
                return ResourceManager.GetString("NoHeaderBlockToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No required method could be found on the type {1} with the name &apos;{0}&apos; or the specified parameters..
        /// </summary>
        internal static string NoMethodFoundOnTheTypeWithName {
            get {
                return ResourceManager.GetString("NoMethodFoundOnTheTypeWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NoOp count on the PDFComponentList has become unbalanced. Please ensure that the count is only incrementd or decrementd evenly..
        /// </summary>
        internal static string NoOpCountOutOfRange {
            get {
                return ResourceManager.GetString("NoOpCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout does not have any open blocks on the page..
        /// </summary>
        internal static string NoOpenBlocksToAppendTo {
            get {
                return ResourceManager.GetString("NoOpenBlocksToAppendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source &apos;{1}&apos; does not contain a command with the specified key &apos;{0}&apos;..
        /// </summary>
        internal static string NoPredefinedCommandWithKey {
            get {
                return ResourceManager.GetString("NoPredefinedCommandWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no configured .net data provider with the name &apos;{0}&apos;..
        /// </summary>
        internal static string NoProviderFactoryWithName {
            get {
                return ResourceManager.GetString("NoProviderFactoryWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link to a remote destination could not be created as the path to the file has not been set (or is empty).
        /// </summary>
        internal static string NoRemoteDestinationSpecifiedOnLink {
            get {
                return ResourceManager.GetString("NoRemoteDestinationSpecifiedOnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XmlDatasource {0} does not has a source file set to load data from and the value of the XmlDocument has not been set..
        /// </summary>
        internal static string NoSourcePathDefinedOnXmlDataSource {
            get {
                return ResourceManager.GetString("NoSourcePathDefinedOnXmlDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current table grid layout does not have any open rows to add layout cells to..
        /// </summary>
        internal static string NoTableRowToAddCellTo {
            get {
                return ResourceManager.GetString("NoTableRowToAddCellTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current text block cannot be retrieved as the current component does not implement the IPDFTextComponent interface..
        /// </summary>
        internal static string NoTextBlockAsCurrentComponentIsNotTextComponent {
            get {
                return ResourceManager.GetString("NoTextBlockAsCurrentComponentIsNotTextComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Type could be found in the namespace &apos;{1}&apos; that declares a component name &apos;{0}&apos;. Please check the file and required type..
        /// </summary>
        internal static string NoTypeFoundWithPDFComponentNameInNamespace {
            get {
                return ResourceManager.GetString("NoTypeFoundWithPDFComponentNameInNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid, sourced licence was not found that supports the restricted operation &apos;{0}&apos;. Please check your license agreement to ensure you are up to date..
        /// </summary>
        internal static string NoValidLicenceFoundForOperation {
            get {
                return ResourceManager.GetString("NoValidLicenceFoundForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current web context available. This provider requires a current web context inorder to function..
        /// </summary>
        internal static string NoWebContextAvailable {
            get {
                return ResourceManager.GetString("NoWebContextAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string NullArgument1 {
            get {
                return ResourceManager.GetString("NullArgument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relation could not be created in command {1} as the child column name has not been set for table {0}.
        /// </summary>
        internal static string NullChildColumnForRelationToTable {
            get {
                return ResourceManager.GetString("NullChildColumnForRelationToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relation could not be created in command {1} as the parent column name has not been set for table {0}.
        /// </summary>
        internal static string NullParentColumnForRelationToTable {
            get {
                return ResourceManager.GetString("NullParentColumnForRelationToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object datasource {1} can only use and execute PDFObjectCommands to load the data. The command &apos;{0}&apos; is not an object command..
        /// </summary>
        internal static string ObjectDataSourceCanOnlyUseObjectCommands {
            get {
                return ResourceManager.GetString("ObjectDataSourceCanOnlyUseObjectCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using the UpdateDocument either the BaseFile must be set, or the orig source path to a valid PDF file must be set..
        /// </summary>
        internal static string OrigSourceIsRequiredForUpdateDocument {
            get {
                return ResourceManager.GetString("OrigSourceIsRequiredForUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page break components are only supported at the root content level of a section..
        /// </summary>
        internal static string PageBreaksAreOnlySupportedAtTheRootSection {
            get {
                return ResourceManager.GetString("PageBreaksAreOnlySupportedAtTheRootSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parsed page content streams can only be object references or arrays of bject references.
        /// </summary>
        internal static string PageContentsCanOnlyByReferencesOrArraysOfReferences {
            get {
                return ResourceManager.GetString("PageContentsCanOnlyByReferencesOrArraysOfReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MediaBox value for a page must be an array of numbers (or an indirect reference to an array of numbers..
        /// </summary>
        internal static string PageMediaboxMustBeAnArray {
            get {
                return ResourceManager.GetString("PageMediaboxMustBeAnArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page owner of a PDFModifyLayoutPage must be a PDFModifyPageBase.
        /// </summary>
        internal static string PageOwnerOfAModifyLayoutMustBeAModifyPage {
            get {
                return ResourceManager.GetString("PageOwnerOfAModifyLayoutMustBeAModifyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page at (zero based) index {0} was not found in the file &apos;{1}&apos;..
        /// </summary>
        internal static string PageToUpdateWasNotFound {
            get {
                return ResourceManager.GetString("PageToUpdateWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent document cannot be null..
        /// </summary>
        internal static string ParentDocumentCannotBeNull {
            get {
                return ResourceManager.GetString("ParentDocumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component must be within the document hierarchy to perform this action. Currently the parent document is null..
        /// </summary>
        internal static string ParentDocumentCannotBeNull1 {
            get {
                return ResourceManager.GetString("ParentDocumentCannotBeNull1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent document of a template must implment the IPDFTemplateParser interface..
        /// </summary>
        internal static string ParentDocumentMustBeTemplateParser {
            get {
                return ResourceManager.GetString("ParentDocumentMustBeTemplateParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path data for a triangle must have 3 and only 3 points..
        /// </summary>
        internal static string PathMustHave3PointsForTriangle {
            get {
                return ResourceManager.GetString("PathMustHave3PointsForTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path resolution stack has become unbalanced and parsing cannot continue..
        /// </summary>
        internal static string PathStackIsUnbalanced {
            get {
                return ResourceManager.GetString("PathStackIsUnbalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDFType can only be initialized with a ASCII string {1} characters long. The string &apos;{0}&apos; is not the correct length..
        /// </summary>
        internal static string PDFTypeStringOnlyNChars {
            get {
                return ResourceManager.GetString("PDFTypeStringOnlyNChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required child element &apos;{0}&apos; was not found on the component definition &apos;{1}&apos;.
        /// </summary>
        internal static string RequiredChildElementNotFountOnElement {
            get {
                return ResourceManager.GetString("RequiredChildElementNotFountOnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required resource container for the {0} component with ID &apos;{1}&apos; cound not be found..
        /// </summary>
        internal static string ResourceContainerOfComponentNotFound {
            get {
                return ResourceManager.GetString("ResourceContainerOfComponentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource container for the {0} component &apos;{1}&apos; was not found. This component can only be rendered as child of a resource container such as a Page or Section..
        /// </summary>
        internal static string ResourceContainerOfComponnetNotFound {
            get {
                return ResourceManager.GetString("ResourceContainerOfComponnetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return type of expression &apos;{0}&apos; is a new XPath navigator. This cannot be assigned to a simple property..
        /// </summary>
        internal static string ReturnTypeOfXPathExpressionCannotBeNavigatorForPropertyEvaluation {
            get {
                return ResourceManager.GetString("ReturnTypeOfXPathExpressionCannotBeNavigatorForPropertyEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SqlDataSource &apos;{1}&apos; can only use SqlCommands to load data. The command &apos;{0}&apos; is not an SqlCommand..
        /// </summary>
        internal static string SqlDataSourceCanOnlyUseSqlCommands {
            get {
                return ResourceManager.GetString("SqlDataSourceCanOnlyUseSqlCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step count cannot be greater than the vertex count..
        /// </summary>
        internal static string StepCountCannotBeGreaterThanVertexCount {
            get {
                return ResourceManager.GetString("StepCountCannotBeGreaterThanVertexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  relation could not be created in command {1} as the table {0} does not contain the column {2}..
        /// </summary>
        internal static string TableDoesNotContainColumn {
            get {
                return ResourceManager.GetString("TableDoesNotContainColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template Component cannot be the root Component. It must be contained within another container..
        /// </summary>
        internal static string TemplateComponentCannotBeRoot {
            get {
                return ResourceManager.GetString("TemplateComponentCannotBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent Component of a template Component must be an instance of an IPDFContainerComponent.
        /// </summary>
        internal static string TemplateComponentParentMustBeContainer {
            get {
                return ResourceManager.GetString("TemplateComponentParentMustBeContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template generator has not been initialised. The InitTemplate method must be called before any instaniation..
        /// </summary>
        internal static string TemplateHasNotBeenInitialised {
            get {
                return ResourceManager.GetString("TemplateHasNotBeenInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TextBlock has not been assigned to the current text component..
        /// </summary>
        internal static string TextBlockIsNotSetOnComponent {
            get {
                return ResourceManager.GetString("TextBlockIsNotSetOnComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text operation flag &apos;{0}&apos; is not supported. Use a full parse to generate spans, divs, and text formats..
        /// </summary>
        internal static string TextOptionTypeIsNotSupported {
            get {
                return ResourceManager.GetString("TextOptionTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout block to be rendered does not have any postion infromation associated with it. The position must be set on the block before it can be rendered..
        /// </summary>
        internal static string ThisBlockDoesNotHaveAnyPostionOptions {
            get {
                return ResourceManager.GetString("ThisBlockDoesNotHaveAnyPostionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout block to be rendered does not have any style information associated with it. The FulStyle must be set before it can be rendered..
        /// </summary>
        internal static string ThisBlockDoesNotHaveAnyStyle {
            get {
                return ResourceManager.GetString("ThisBlockDoesNotHaveAnyStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document layout does not correspond to this PDFDocument and you cannot output a layout from a different document component..
        /// </summary>
        internal static string TryingToOutputADifferentDocumentLayout {
            get {
                return ResourceManager.GetString("TryingToOutputADifferentDocumentLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; could not be found or loaded on object command &apos;{1}&apos; in the data source {2}. Are you missing an assembly reference..
        /// </summary>
        internal static string TypeCouldNotBeFoundForObjectData {
            get {
                return ResourceManager.GetString("TypeCouldNotBeFoundForObjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component {0} is registered as a licensed component, but does not have a public key assigned on it&apos;s attribute.
        /// </summary>
        internal static string TypeDoesNotHavePublicKeyForLicence {
            get {
                return ResourceManager.GetString("TypeDoesNotHavePublicKeyForLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component {0} is not registered with a license key attribute..
        /// </summary>
        internal static string TypeIsNotRegisteredWithLicensedComponentAttribute {
            get {
                return ResourceManager.GetString("TypeIsNotRegisteredWithLicensedComponentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type name of the class containing the method to call for the Object Command &apos;{0}&apos; has not been set in the data source &apos;{1}&apos;.
        /// </summary>
        internal static string TypeNameNotSetOnObjectDataSource {
            get {
                return ResourceManager.GetString("TypeNameNotSetOnObjectDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data stack has become unbalanced. Entries have been added or removed out of sequence..
        /// </summary>
        internal static string UnbalancedDataStack {
            get {
                return ResourceManager.GetString("UnbalancedDataStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outline stack has become unbalanced. Entries have been added or removed out of sequence..
        /// </summary>
        internal static string UnbalancedOutlineStack {
            get {
                return ResourceManager.GetString("UnbalancedOutlineStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style stack has become unbalanced. Entries have been added or removed out of sequence..
        /// </summary>
        internal static string UnbalancedStyleStack {
            get {
                return ResourceManager.GetString("UnbalancedStyleStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown artefact for the names dictionary. All Artefacts must implement the ICategorisedArtefactNamesEntry interface if they are to be stored in the Names dictionary of the documents catalog..
        /// </summary>
        internal static string UnknownArtefactForNamesDictionary {
            get {
                return ResourceManager.GetString("UnknownArtefactForNamesDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document format &apos;{0}&apos; is not a known or supported format. Rendering cannot contine..
        /// </summary>
        internal static string UnknownDocumentFormat {
            get {
                return ResourceManager.GetString("UnknownDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XSLT transformation file could not be loaded from the mapped path &apos;{0}&apos;.
        /// </summary>
        internal static string XSLTCouldNotBeLoadedFromPath {
            get {
                return ResourceManager.GetString("XSLTCouldNotBeLoadedFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to an XSLT file or an XSLCompiled transform has not been set on the Transform extension for the datasource {0}..
        /// </summary>
        internal static string XSLTPathOrTransformerNotSetOnInstance {
            get {
                return ResourceManager.GetString("XSLTPathOrTransformerNotSetOnInstance", resourceCulture);
            }
        }
    }
}
