using System;
using System.Linq;
using Scryber.Styles;
using Scryber.Components;
using Scryber.Drawing;
using Scryber.PDF;
using Scryber.PDF.Layout;

namespace Scryber.Html.Components
{
    [PDFParsableComponent("select")]
    public class HTMLSelect : FormInputField
    {
        private HTMLOptionList _items;
        private string _value;
        
        [PDFAttribute("class")]
        public override string StyleClass { get => base.StyleClass; set => base.StyleClass = value; }

        [PDFAttribute("style")]
        public override Style Style { get => base.Style; set => base.Style = value; }
        

        /// <summary>
        /// Global Html hidden attribute used with xhtml as hidden='hidden'
        /// </summary>
        [PDFAttribute("hidden")]
        public string Hidden
        {
            get
            {
                if (this.Visible)
                    return string.Empty;
                else
                    return "hidden";
            }
            set
            {
                if (string.IsNullOrEmpty(value) || value != "hidden")
                    this.Visible = true;
                else
                    this.Visible = false;
            }
        }

        /// <summary>
        /// Take the value out of writing to the
        /// </summary>
        [PDFAttribute("value")]
        public override string Value
        {
            get => _value;
            set => _value = value;
        }

        public string SelectedText
        {
            get{ return base.Value; }
            set{ base.Value = value; }
        }


        [PDFAttribute("title")]
        public override string OutlineTitle
        {
            get => base.OutlineTitle;
            set => base.OutlineTitle = value;
        }
        
        //Overrides FormInputField.Size on purpose - <select size> means "number of visible rows"
        //(a listbox row count), an entirely different HTML semantic from <input size>'s
        //"roughly N average character widths" that the base property now exists for.
        [PDFAttribute("size")]
        public override int Size
        {
            get;
            set;
        }
        
        

        /// <summary>
        /// The &lt;option&gt; children, as the parser's element target for this select - mirrors
        /// HTMLColGroup.Columns/HTMLColList. A strongly-typed ComponentWrappingList rather than a
        /// plain ComponentList override, so it also picks up options generated by {{#each}}/data-bind
        /// templates (the same underlying InnerContent both are backed by), and options nested inside
        /// any future IInvisibleContainer grouping (e.g. optgroup) via the base wrapping list's recursion.
        /// </summary>
        [PDFArray(typeof(HTMLOption))]
        [PDFElement("")]
        public HTMLOptionList Items
        {
            get
            {
                if (null == _items)
                    _items = new HTMLOptionList(this.InnerContent);
                return _items;
            }
        }

        /// <summary>
        /// Without the PDF /Ff Combo bit, a Choice field defaults to a list box - every /Opt entry
        /// drawn stacked within the field's own (single-line-sized) rect, which is exactly the
        /// "reader draws all the options crammed into the control" symptom. A plain HTML
        /// &lt;select&gt; (no "multiple") is a dropdown - the PDF equivalent is a combo box, so Combo
        /// is set by default here and only cleared when multiple= makes this a real list box instead.
        /// </summary>
        [PDFAttribute("multiple")]
        public HtmlBoolean Multiple
        {
            get { return (this.Options & FormFieldOptions.Multiselect) == FormFieldOptions.Multiselect; }
            set
            {
                if (value)
                {
                    this.Options |= FormFieldOptions.Multiselect;
                    this.Options &= ~FormFieldOptions.Combo;
                }
                else
                {
                    this.Options &= ~FormFieldOptions.Multiselect;
                    this.Options |= FormFieldOptions.Combo;
                }
            }
        }

        /// <summary>
        /// The choices for this select, harvested from its &lt;option&gt; children during data binding.
        /// </summary>
        public FormFieldOptionList Choices { get; private set; }

        public HTMLSelect() : this(HTMLObjectTypes.Select)
        {
        }

        protected HTMLSelect(ObjectType type) : base(type)
        {
            this.FieldType = FormInputFieldType.Choice;
            this.Choices = new FormFieldOptionList();
            this.Options |= FormFieldOptions.Combo;
        }
        
        

        /// <summary>
        /// Harvesting has to wait until OnPreLayout, not OnDataBound - {{#each}}-bound options are
        /// generated into a TemplateInstance by ForEach's own DataBind, but that hasn't necessarily
        /// completed yet by the time this component's own OnDataBound fires. OnPreLayout is a
        /// separate, dedicated pass that cascades over the whole tree after data binding is fully
        /// finished and before layout begins (see ContainerComponent.RegisterPreLayout/Document.cs),
        /// so by then every option - static or template-generated - is guaranteed to be in Items.
        /// </summary>
        protected override void OnPreLayout(LayoutContext context)
        {
            base.OnPreLayout(context);

            FormFieldOption selected = null;
            
            foreach (var option in this.Items.ToList())
            {
                var value = string.IsNullOrEmpty(option.Value) ? option.Label : option.Value;
                var label = string.IsNullOrEmpty(option.Label) ? value : option.Label;

                var ffo = new FormFieldOption { Value = value, Label = label, Selected = option.Selected };
                this.Choices.Add(ffo);

                //Items.Remove only ever removes a direct child of this select's own InnerContent -
                //a {{#each}}-bound option instead lives inside a generated TemplateInstance, so it
                //has to come out of its own actual parent's content, not this select's.

                if (ffo.Selected)
                    selected = ffo;
            }

            if (string.IsNullOrEmpty(this.Value))
            {
                selected = this.Choices.FirstOrDefault(c => c.Selected) ?? this.Choices.FirstOrDefault();
            }
            
            //As we have captured the contents as form field options, we can remove the inner content, and then just set the value.
            if (!this.Multiple.Value)
            {
                this.InnerContent.Clear();

                //Will add a literal for the current value.
                if (null != selected)
                {
                    this.Value = selected.Value;
                    this.SelectedText = selected.Label;
                }
            }
        }

        protected override PDFAcrobatFormFieldWidget GetFieldEntry(ContextBase context)
        {
            var entry = base.GetFieldEntry(context);
            entry.Choices = this.Choices;
            return entry;
        }

        protected override IPDFLayoutEngine CreateLayoutEngine(IPDFLayoutEngine parent, PDFLayoutContext context, Style style)
        {
            return new LayoutEngineSelect(this, parent);
        }
    }
}
